### PR TITLE
fix the typo

### PR DESCRIPTION
**Pull request by worthmine**
$res may be $ret

### CODE REVIEW

**Comment by yappo** [comment]
README.md is an auto-generated file generated from https://github.com/line/line-bot-sdk-perl/blob/master/lib/LINE/Bot/API.pm. Please send p-r to https://github.com/line/line-bot-sdk-perl/blob/master/lib/LINE/Bot/API.pm instead.

**Comment by yappo** [comment]
BTW, Did you sign to the ICLA? https://feedback.line.me/enquete/public/919-h9Yqmr1u

Please submit that if you didn't submit yet.
I will merge this pull request after you submitted the ICLA.

**Comment by worthmine** [comment]
I did it!
And thank you for inviting ICLA. I did submit that, too.

**Comment by yappo** [comment]
Thank you for your contributing!

**Pull request merged**
